package:
  name: nimble
  version: "0.5.1"

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy>=1.14
    - packaging>=20.0
    - tomli>=2.0
  run:
    - python {{ python }}
    - numpy>=1.14
    - packaging>=20.0
    - tomli>=2.0

outputs:
  - name: nimble
  - name: nimble-quickstart
    requirements:
      build:
      run:
        - python
        - pandas>=0.24
        - scipy>=1.1
        - matplotlib>=3.1
        - cloudpickle>=1.0
        - requests>2.12
        - h5py>=2.10
        - python-dateutil>=2.6
        - scikit-learn>=1.0
        - {{ pin_subpackage('nimble', max_pin="x.x.x.x") }}
      run_constrained:
        - keras>=2.4
        - tensorflow>=2.0
        - hyperopt>=0.2
    test:
      imports:
        - nimble

test:
  imports:
    - nimble

about:
  home: https://www.nimbledata.org
