name: Test Workflow

on:
  workflow_call:
    inputs:
      # The name of the artifact containing the wheels
      saveNameWheel:
        required: true
        type: string
      # The name of the artifact containing the conda channel
      saveNameConda:
        required: true
        type: string

jobs:

  test-workflow:
    name: ${{ matrix.pyVer}} for ${{ matrix.os}}
    # This will automatically split off concurrent jobs running-on each value
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        pyVer: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyVer}}
          cache: pip
          cache-dependency-path: pyproject.toml

      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.saveNameWheel}}
    
      - name: Move Wheels to docs source
        shell: bash
        run: mv *.whl ./documentation/source/wheels

      - name: install nimble and dependencies
        run: 
          pip install pylint==2.14.0
          pip install pytest
          pip install keras tensorflow
          pip install nimble[quickstart] --find-links=./documentation/source/wheels # Only if needed 

      - name: Run pytest
        run: pytest -p no:cacheprovider
